### ISSUE TITLE
Wrongly claims that TREZOR bootloader is deliberately non-working

### ISSUE THREAD

**Issue by saleemrashid** [karek314/trezor-diy-development-board#1]
This is actually a mistake that no one realised. It's due to how the RNG is initialized and was discovered and fixed by @mruddy, see trezor/trezor-mcu#150.

**Comment by karek314** [comment]
Fixed readme, i haven't investigated issue behind that, however after building prototypes i have encountered this infinite loading loop and reported that to their team, one of them, not sure who exactly as i don't remember, claimed that it might be hardware issue, personally i won't believe it wasn't on purpose taking in count that they didn't wanted to publish firmware at beginning. This attitude may explain thinking that it was on purpose to make harder creating cheap copies.

**Comment by saleemrashid** [comment]
It's a hardware issue because your board must not have an initialized RNG. The RNG was initialized later in the code, which was a mistake. Originally, anyway, the bootloader didn't even use a stack guard.

You can verify that the TREZOR is running a bootloader compiled from this code by dumping the bootloader from firmware and then compiling bootloader from source code.

**Comment by saleemrashid** [comment]
You'll want to pull the latest bootloader, by the way, where this is fixed.

**Comment by karek314** [comment]
That explains everything, no need to do - i have just made few copies for friends, chips are locked anyways.

**Comment by prusnak** [comment]
Offtopic, but to my best knowledge all changes you have in your trezor-mcu fork have been merged to upstream, so it might make sense to delete your fork and point people to original sources instead in README.

**Comment by karek314** [comment]
@prusnak , Right - i have corrected url as well.
